"""empty message

Revision ID: 4cd1a64c66c6
Revises: 
Create Date: 2023-05-14 14:48:59.590160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd1a64c66c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regName', sa.String(length=200), nullable=False),
    sa.Column('regPhone', sa.String(length=200), nullable=False),
    sa.Column('regEmail', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petName', sa.String(length=200), nullable=False),
    sa.Column('petBreed', sa.String(length=200), nullable=False),
    sa.Column('petBirth', sa.String(length=200), nullable=False),
    sa.Column('petProfile', sa.String(length=400), nullable=False),
    sa.Column('regId', sa.Integer(), nullable=True),
    sa.Column('uniqNum', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['regId'], ['registrant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    op.drop_table('registrant')
    # ### end Alembic commands ###
